SWF   compressed: yes, version: 7, length: 34175, rate: 3072
TAG TagKind_SetBackgroundColor   length: 3
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineShape   length: 42
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineSprite   length: 21
TAG TagKind_DefineShape3   length: 29
TAG TagKind_DefineShape   length: 26
TAG TagKind_DefineShape3   length: 49
TAG TagKind_DefineShape3   length: 71
TAG TagKind_DefineSprite   length: 138
TAG TagKind_ExportAssets   length: 19
TAG TagKind_DefineShape3   length: 29
TAG TagKind_DefineSprite   length: 170
TAG TagKind_ExportAssets   length: 19
TAG TagKind_DefineSprite   length: 100
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineSprite   length: 143
TAG TagKind_ExportAssets   length: 11
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineFont2   length: 15
TAG TagKind_DefineEditText   length: 37
TAG TagKind_DefineSprite   length: 54
TAG TagKind_DefineVideoStream   length: 10
TAG TagKind_DefineSprite   length: 27
TAG TagKind_DefineEditText   length: 38
TAG TagKind_DefineSprite   length: 54
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineSprite   length: 90
TAG TagKind_ExportAssets   length: 17
TAG TagKind_DefineEditText   length: 42
TAG TagKind_DefineSprite   length: 54
TAG TagKind_ExportAssets   length: 11
TAG TagKind_DefineSprite   length: 22
TAG TagKind_DefineSprite   length: 22
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineSprite   length: 20
TAG TagKind_DefineSprite   length: 87
TAG TagKind_ExportAssets   length: 13
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineSprite   length: 109
TAG TagKind_DefineSprite   length: 86
TAG TagKind_DefineSprite   length: 108
TAG TagKind_DefineSprite   length: 77
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineShape3   length: 29
TAG TagKind_DefineSprite   length: 22
TAG TagKind_DefineSprite   length: 21
TAG TagKind_DefineSprite   length: 145
TAG TagKind_ExportAssets   length: 17
TAG TagKind_ExportAssets   length: 11
TAG TagKind_ExportAssets   length: 13
TAG TagKind_DefineSprite   length: 109
TAG TagKind_DefineSprite   length: 88
TAG TagKind_DefineSprite   length: 110
TAG TagKind_DefineSprite   length: 84
TAG TagKind_ExportAssets   length: 16
TAG TagKind_DefineSprite   length: 22
TAG TagKind_DefineFont2   length: 2157
TAG TagKind_DefineEditText   length: 39
TAG TagKind_DefineEditText   length: 41
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineShape3   length: 237
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineShape3   length: 237
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineShape3   length: 351
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineSprite   length: 157
TAG TagKind_ExportAssets   length: 17
TAG TagKind_DefineSprite   length: 207
TAG TagKind_ExportAssets   length: 13
TAG TagKind_DefineShape3   length: 30
TAG TagKind_DefineShape3   length: 425
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 28
TAG TagKind_DefineShape   length: 36
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 14
TAG TagKind_DefineSprite   length: 60
TAG TagKind_ExportAssets   length: 21
TAG TagKind_ExportAssets   length: 28
TAG TagKind_ExportAssets   length: 14
TAG TagKind_DefineSprite   length: 71
TAG TagKind_ExportAssets   length: 19
TAG TagKind_DefineShape3   length: 32
TAG TagKind_DefineShape   length: 39
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 15
TAG TagKind_ExportAssets   length: 15
TAG TagKind_DefineSprite   length: 35
TAG TagKind_ExportAssets   length: 24
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 14
TAG TagKind_ExportAssets   length: 14
TAG TagKind_DefineSprite   length: 35
TAG TagKind_ExportAssets   length: 23
TAG TagKind_DefineSprite   length: 70
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineShape3   length: 602
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 27
TAG TagKind_ExportAssets   length: 14
TAG TagKind_DefineSprite   length: 45
TAG TagKind_ExportAssets   length: 23
TAG TagKind_DefineShape3   length: 438
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 26
TAG TagKind_ExportAssets   length: 14
TAG TagKind_DefineSprite   length: 60
TAG TagKind_ExportAssets   length: 23
TAG TagKind_ExportAssets   length: 21
TAG TagKind_ExportAssets   length: 28
TAG TagKind_ExportAssets   length: 14
TAG TagKind_DefineSprite   length: 66
TAG TagKind_ExportAssets   length: 27
TAG TagKind_DefineSprite   length: 69
TAG TagKind_ExportAssets   length: 19
TAG TagKind_ExportAssets   length: 27
TAG TagKind_ExportAssets   length: 14
TAG TagKind_DefineSprite   length: 56
TAG TagKind_ExportAssets   length: 21
TAG TagKind_ExportAssets   length: 26
TAG TagKind_ExportAssets   length: 14
TAG TagKind_DefineSprite   length: 71
TAG TagKind_ExportAssets   length: 21
TAG TagKind_ExportAssets   length: 19
TAG TagKind_ExportAssets   length: 28
TAG TagKind_ExportAssets   length: 14
TAG TagKind_DefineSprite   length: 77
TAG TagKind_ExportAssets   length: 25
TAG TagKind_DefineSprite   length: 70
TAG TagKind_ExportAssets   length: 17
TAG TagKind_DefineSprite   length: 239
TAG TagKind_ExportAssets   length: 13
TAG TagKind_DefineSprite   length: 37
TAG TagKind_DefineSprite   length: 128
TAG TagKind_ExportAssets   length: 24
TAG TagKind_DefineShape3   length: 73
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineShape3   length: 150
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineShape3   length: 205
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 20
TAG TagKind_DefineShape3   length: 73
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 20
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineShape3   length: 30
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineSprite   length: 44
TAG TagKind_ExportAssets   length: 24
TAG TagKind_DefineSprite   length: 70
TAG TagKind_ExportAssets   length: 15
TAG TagKind_DefineShape3   length: 266
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 20
TAG TagKind_DefineShape3   length: 149
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 20
TAG TagKind_ExportAssets   length: 18
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineSprite   length: 44
TAG TagKind_ExportAssets   length: 24
TAG TagKind_DefineSprite   length: 70
TAG TagKind_ExportAssets   length: 15
TAG TagKind_DefineShape2   length: 71
TAG TagKind_DefineSprite   length: 193
TAG TagKind_ExportAssets   length: 19
TAG TagKind_ExportAssets   length: 11
TAG TagKind_DefineSprite   length: 22
TAG TagKind_DefineSprite   length: 22
TAG TagKind_DefineSprite   length: 20
TAG TagKind_DefineSprite   length: 89
TAG TagKind_ExportAssets   length: 13
TAG TagKind_DefineSprite   length: 109
TAG TagKind_DefineSprite   length: 86
TAG TagKind_DefineSprite   length: 108
TAG TagKind_DefineSprite   length: 82
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineSprite   length: 21
TAG TagKind_DefineSprite   length: 21
TAG TagKind_DefineSprite   length: 149
TAG TagKind_ExportAssets   length: 17
TAG TagKind_ExportAssets   length: 11
TAG TagKind_ExportAssets   length: 13
TAG TagKind_DefineSprite   length: 109
TAG TagKind_DefineSprite   length: 88
TAG TagKind_DefineSprite   length: 110
TAG TagKind_DefineSprite   length: 89
TAG TagKind_ExportAssets   length: 17
TAG TagKind_DefineSprite   length: 22
TAG TagKind_DefineEditText   length: 39
TAG TagKind_DefineEditText   length: 41
TAG TagKind_DefineShape3   length: 239
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineShape3   length: 239
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineShape3   length: 351
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineSprite   length: 148
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineSprite   length: 226
TAG TagKind_ExportAssets   length: 13
TAG TagKind_ExportAssets   length: 21
TAG TagKind_ExportAssets   length: 19
TAG TagKind_ExportAssets   length: 21
TAG TagKind_ExportAssets   length: 19
TAG TagKind_ExportAssets   length: 17
TAG TagKind_DefineSprite   length: 239
TAG TagKind_ExportAssets   length: 13
TAG TagKind_DefineSprite   length: 37
TAG TagKind_ExportAssets   length: 24
TAG TagKind_ExportAssets   length: 18
TAG TagKind_ExportAssets   length: 18
TAG TagKind_ExportAssets   length: 15
TAG TagKind_ExportAssets   length: 15
TAG TagKind_DefineShape2   length: 71
TAG TagKind_DefineSprite   length: 193
TAG TagKind_ExportAssets   length: 19
TAG TagKind_DefineShape3   length: 30
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 13
TAG TagKind_DefineEditText   length: 29
TAG TagKind_ExportAssets   length: 11
TAG TagKind_ExportAssets   length: 13
TAG TagKind_ExportAssets   length: 13
TAG TagKind_ExportAssets   length: 13
TAG TagKind_ExportAssets   length: 19
TAG TagKind_DefineSprite   length: 854
TAG TagKind_ExportAssets   length: 20
TAG TagKind_DefineSprite   length: 349
TAG TagKind_ExportAssets   length: 18
TAG TagKind_ExportAssets   length: 17
TAG TagKind_ExportAssets   length: 20
TAG TagKind_ExportAssets   length: 19
TAG TagKind_ExportAssets   length: 19
TAG TagKind_ExportAssets   length: 15
TAG TagKind_ExportAssets   length: 15
TAG TagKind_ExportAssets   length: 24
TAG TagKind_ExportAssets   length: 13
TAG TagKind_ExportAssets   length: 18
TAG TagKind_ExportAssets   length: 17
TAG TagKind_ExportAssets   length: 13
TAG TagKind_ExportAssets   length: 17
TAG TagKind_ExportAssets   length: 16
TAG TagKind_ExportAssets   length: 17
TAG TagKind_ExportAssets   length: 21
TAG TagKind_ExportAssets   length: 17
TAG TagKind_ExportAssets   length: 21
TAG TagKind_ExportAssets   length: 13
TAG TagKind_ExportAssets   length: 13
TAG TagKind_ExportAssets   length: 17
TAG TagKind_ExportAssets   length: 19
TAG TagKind_ExportAssets   length: 21
TAG TagKind_ExportAssets   length: 11
TAG TagKind_ExportAssets   length: 21
TAG TagKind_ExportAssets   length: 19
TAG TagKind_ExportAssets   length: 19
TAG TagKind_DefineShape   length: 33
TAG TagKind_DefineShape   length: 36
TAG TagKind_DefineButton2   length: 61
TAG TagKind_DefineSprite   length: 45
TAG TagKind_ExportAssets   length: 29
TAG TagKind_DefineSprite   length: 29
TAG TagKind_ExportAssets   length: 10
TAG TagKind_DefineShape3   length: 255
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 31
TAG TagKind_DefineShape3   length: 99
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 28
TAG TagKind_DefineShape2   length: 103
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 32
TAG TagKind_DefineShape2   length: 103
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 32
TAG TagKind_DefineShape3   length: 412
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 17
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 17
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 15
TAG TagKind_DefineSprite   length: 49
TAG TagKind_ExportAssets   length: 20
TAG TagKind_DefineShape3   length: 129
TAG TagKind_DefineShape   length: 166
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineShape   length: 51
TAG TagKind_DefineSprite   length: 36
TAG TagKind_ExportAssets   length: 31
TAG TagKind_DefineSprite   length: 20
TAG TagKind_ExportAssets   length: 29
TAG TagKind_DefineShape3   length: 158
TAG TagKind_DefineSprite   length: 28
TAG TagKind_ExportAssets   length: 29
TAG TagKind_DefineShape3   length: 170
TAG TagKind_DefineSprite   length: 28
TAG TagKind_ExportAssets   length: 29
TAG TagKind_DefineShape3   length: 52
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 25
TAG TagKind_DefineShape3   length: 52
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 23
TAG TagKind_DefineShape3   length: 299
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineShape3   length: 572
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 19
TAG TagKind_DefineShape3   length: 183
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 17
TAG TagKind_DefineSprite   length: 63
TAG TagKind_ExportAssets   length: 15
TAG TagKind_DefineShape   length: 29
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 22
TAG TagKind_DefineShape3   length: 74
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 24
TAG TagKind_DefineShape   length: 26
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineShape2   length: 47
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 19
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineSprite   length: 63
TAG TagKind_ExportAssets   length: 19
TAG TagKind_DefineShape   length: 166
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 36
TAG TagKind_DefineShape2   length: 88
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 20
TAG TagKind_DefineShape2   length: 86
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineShape2   length: 93
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 22
TAG TagKind_DefineSprite   length: 78
TAG TagKind_ExportAssets   length: 22
TAG TagKind_DefineSprite   length: 18
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineSprite   length: 114
TAG TagKind_DefineSprite   length: 46
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineSprite   length: 44
TAG TagKind_ExportAssets   length: 16
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineSprite   length: 114
TAG TagKind_DefineSprite   length: 48
TAG TagKind_ExportAssets   length: 17
TAG TagKind_DefineSprite   length: 44
TAG TagKind_ExportAssets   length: 15
TAG TagKind_DefineShape   length: 29
TAG TagKind_DefineSprite   length: 113
TAG TagKind_ExportAssets   length: 23
TAG TagKind_DefineShape   length: 28
TAG TagKind_DefineSprite   length: 122
TAG TagKind_ExportAssets   length: 23
TAG TagKind_DefineSprite   length: 23
TAG TagKind_ExportAssets   length: 22
TAG TagKind_ExportAssets   length: 23
TAG TagKind_DefineSprite   length: 21
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineSprite   length: 84
TAG TagKind_ExportAssets   length: 22
TAG TagKind_DefineShape   length: 29
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 23
TAG TagKind_DefineShape   length: 29
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 22
TAG TagKind_DefineShape   length: 35
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 22
TAG TagKind_DefineShape   length: 35
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineShape   length: 49
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 22
TAG TagKind_DefineShape   length: 49
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineShape   length: 43
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineSprite   length: 85
TAG TagKind_ExportAssets   length: 15
TAG TagKind_DefineShape2   length: 145
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineShape3   length: 444
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineSprite   length: 32
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineShape2   length: 145
TAG TagKind_DefineSprite   length: 16
TAG TagKind_DefineSprite   length: 26
TAG TagKind_ExportAssets   length: 20
TAG TagKind_DefineSprite   length: 26
TAG TagKind_ExportAssets   length: 20
TAG TagKind_DefineSprite   length: 8
TAG TagKind_ExportAssets   length: 24
TAG TagKind_DefineBitsLossless2   length: 137
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineShape   length: 32
TAG TagKind_DefineSprite   length: 16
TAG TagKind_ExportAssets   length: 18
TAG TagKind_DefineEditText   length: 29
TAG TagKind_DefineSprite   length: 35
TAG TagKind_ExportAssets   length: 14
TAG TagKind_DefineEditText   length: 29
TAG TagKind_DefineSprite   length: 40
TAG TagKind_ExportAssets   length: 21
TAG TagKind_DefineEditText   length: 29
TAG TagKind_DefineSprite   length: 35
TAG TagKind_ExportAssets   length: 13
TAG TagKind_DefineEditText   length: 29
TAG TagKind_DefineSprite   length: 40
TAG TagKind_ExportAssets   length: 10
TAG TagKind_DefineFont2   length: 15
TAG TagKind_DefineEditText   length: 106
TAG TagKind_DefineSprite   length: 123
TAG TagKind_ExportAssets   length: 13
TAG TagKind_PlaceObject2   length: 15
TAG TagKind_DefineSprite   length: 6
TAG TagKind_ExportAssets   length: 43
TAG TagKind_DoInitAction   length: 791
TAG TagKind_DefineSprite   length: 6
TAG TagKind_ExportAssets   length: 36
TAG TagKind_DoInitAction   length: 681
TAG TagKind_DoInitAction   length: 73
TAG TagKind_DoInitAction   length: 131
TAG TagKind_DoInitAction   length: 121
TAG TagKind_DoInitAction   length: 106
TAG TagKind_DoInitAction   length: 123
TAG TagKind_DoInitAction   length: 131
TAG TagKind_DoInitAction   length: 127
TAG TagKind_DoInitAction   length: 126
TAG TagKind_DoInitAction   length: 127
TAG TagKind_DoInitAction   length: 123
TAG TagKind_DoInitAction   length: 134
TAG TagKind_DoInitAction   length: 130
TAG TagKind_DoInitAction   length: 126
TAG TagKind_DoInitAction   length: 134
TAG TagKind_DoInitAction   length: 125
TAG TagKind_DoInitAction   length: 125
TAG TagKind_DoInitAction   length: 129
TAG TagKind_DoInitAction   length: 123
TAG TagKind_DoInitAction   length: 131
TAG TagKind_DoInitAction   length: 127
TAG TagKind_DoInitAction   length: 127
TAG TagKind_DoInitAction   length: 128
TAG TagKind_DoInitAction   length: 123
TAG TagKind_DoInitAction   length: 129
TAG TagKind_DoInitAction   length: 109
TAG TagKind_DoInitAction   length: 107
TAG TagKind_DoInitAction   length: 119
TAG TagKind_DoInitAction   length: 129
TAG TagKind_DoInitAction   length: 103
TAG TagKind_DoInitAction   length: 103
TAG TagKind_DoInitAction   length: 102
TAG TagKind_DoInitAction   length: 99
TAG TagKind_DoInitAction   length: 129
TAG TagKind_ShowFrame   length: 0